global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'nodejs-service'
    static_configs:
      - targets: ['nodejs:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'golang-service'
    static_configs:
      - targets: ['golang:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'python-service'
    static_configs:
      - targets: ['python:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s